### ISSUE TITLE
Should RFC-028 be Standards Track?

### ISSUE THREAD

**Issue by philoserf** [chef/chef-rfc#110]
Since [RFC-028](https://github.com/chef/chef-rfc/blob/master/rfc028-mailing-list-migration.md) can be implimented it seems to me it should be a "Standards Track" RFC as decribed in [RFC-000](https://github.com/chef/chef-rfc/blob/master/rfc000-rfc-process.md). As is one can see it is "Accepted" and not know if it has been implemented.

**Comment by coderanger** [comment]
No, it doesn't describe a code change or feature. It's status is a bit wonky because it was accepted and then the migration failed so we re-accepted it a second time.
