### ISSUE TITLE
[Chef 12] Support nested directories

### ISSUE THREAD

**Issue by sethvargo** [chef/chef-rfc#24]
#### Support nested directorires
 * **Breaks Backwards Compatibility? (Workstation):** No
 * **Breaks Backwards Compatibility? (Cookbooks):**  No
 * **User Benefit:** High
  * Short description of the benefit: As cookbooks become more complex, having the ability to logically group files in folders is incredibly useful, especially libraries. However, it would also be useful to group recipes and other resources as well.
 * **Impact:** None
  * Short description of the impact: This should be fully-BC, so there is no impact. There is a residual impact that cookbooks which implement this pattern would not be BC.

**Comment by jkeiser** [comment]
I don't see an acceptance for this, but I'd love to see something more detailed--did I miss an RFC?  Is there one?

**Comment by ranjib** [comment]
@jkeiser nope, there isn't one. @sethvargo do you plan to reformat this one? or raise another one?

This one provides the template:
https://github.com/chef/chef-rfc/blob/master/rfc000-rfc-process.md

**Comment by jkeiser** [comment]
I'm building one now :)  It turns out we've already merged something that allows Chef client to upload a cookbook with nested library files; I'm adding something to make it useful in a way I want.

**Comment by jkeiser** [comment]
Thus the RFC I'm building doesn't intersect with this, but it does make this RFC (and the merged patch) much more useful.  One minute.

**Comment by jkeiser** [comment]
https://github.com/chef/chef-rfc/pull/93 is filed for autoloading.  If I read https://github.com/chef/chef/pull/2129#issuecomment-57237381 correctly, nested libraries are already possible (though I'm unclear on the load order or whether the nested directories are loaded).

**Comment by jkeiser** [comment]
I think that might mean we can close this issue--@sethvargo does chef/chef#2129 fulfill what you were after?

**Comment by johntdyer** [comment]
if I am reading chef/chef#2129 correctly its scope is limited to strictly libraries, and I believe @sethvargo's intent on this issue was to support other resources as well, including such as recipes.

**Comment by dblessing** [comment]
@jkeiser I agree w/ @johntdyer - this should be kept open. https://github.com/chef/chef/pull/2129 does not address this RFC.

**Comment by jkeiser** [comment]
Ah!  I missed that this was for all directories.  We need a real RFC though.

- files/ and templates/ are already hierarchical
- libraries/ is covered by chef/chef#2129 and autoloading behavior is addressed in #93.
- What does it mean for recipes/ to have subfolders?  That requires a specific RFC explaining how you would address them in a run list and include_recipe ...
- What does it mean for resources/ providers/ and definitions/ to have subfolders?  Given Chef's currently flat resources hierarchy (which is a completely separate issue from this), I don't think these make sense.

So what we're left with, is someone needs to write an RFC for recipes/ that explains not just "let us have nested recipes," but what it means.

Have I missed any others?

**Comment by jkeiser** [comment]
Unless we think this RFC really means "just stop trying to restrict what files go into the cookbook, and let any subdirectory and any file in any directory be stored in a cookbook."  Does that mean we'd allow other top level directories as well?

**Comment by johntdyer** [comment]
I guess let me clarify what I would like first, to make sure we are on the same page... 

I'd love to see a directory structure like this:

```
|------ service
|        |------ recipes
|        |        |____ default.rb
|        |        |____ service.rb
|        |        |____ client
|        |                  |______ client.rb
|        |        |____ utils
|        |                  |______ utils.rb
```

and then be allowed to reference those recipes like this:

* `recipe[service]`
* `recipe[service::service]`
* `recipe[service::client/client]`
* `recipe[service::utils/utils]`

**Comment by dblessing** [comment]
@johntdyer I think your directory structure is right on. For references, why not `recipe[service::client::client]`? Also, I think Chef should handle this type of thing:

```
|------ service
|        |------ recipes
|        |        |____ default.rb
|        |        |____ service.rb
|        |        |____ client.rb
|        |        |____ client
|        |                  |______ client.rb
|        |        |____ utils
|        |                  |______ utils.rb
```

Which results in the following valid recipe references: `recipe[service::client]` and `recipe[service::client::client]`.

I'm willing to help with an RFC but I'm entirely new to the process. If anyone else is willing to help, please let me know.

**Comment by lamont-granquist** [comment]
I would definitely like to see cookbooks treated more like tarballs by cookbook upload/download and the cookbook synchronizer.  So that means getting rid of segments and treating all directories as recursive.

That alone is probably worth an RFC.   Then there's a question of what semantically you do with different subdirectories.  So extending the recipe syntax to support subdirs is probably an RFC of its own.

**Comment by dblessing** [comment]
I drafted an RFC in an effort to keep things moving. Please provide feedback :smile:

**Comment by coderanger** [comment]
:thumbsup: on less validation on the server and more in the uploader tools. Way faster to iterate on things that way.

**Comment by jkeiser** [comment]
I am totally on board with the "absolutely no constraints on cookbooks" idea. And glad we are separating semantics of individual directories. This needs to become an RFC rather than an issue to move full nested support forward, but I get it now, thanks for the clarification!

**Comment by jamesgaddum** [comment]
:+1:

**Comment by thommay** [comment]
The community decided that we weren't going to support nested directories, as per the RFC discussed in #102 .
