### ISSUE TITLE
[Chef 12] Create a `package_repo` resource

### ISSUE THREAD

**Issue by jtimberman** [chef/chef-rfc#30]
Potential providers:

* yum
* apt
* homebrew (taps)
* IPS 
* rubygems

This was brought up on issue #28. Moving it here for additional discussion.

#### Create a package_repo resource

* **Breaks Backwards Compatibility? (Workstation):** No
* **Breaks Backwards Compatibility? (Cookbooks):**  No
* **User Benefit:** High
  * Short description of the benefit: Having package repository resource/provider available in core Chef would be a huge benefit to remove the dependency on the `yum`, `apt`, and other cookbooks.
* **Impact:** Low
  * Short description of the impact: The only impact is that users who wish to use the new resource would opt into using it by writing the new resource in their recipes. Users can continue using the existing cookbooks until they're ready to migrate.

**Comment by thommay** [comment]
Closing in favour of the pull request version #98
