### ISSUE TITLE
[Chef 12] Specify gems to be loaded with Chef

### ISSUE THREAD

**Issue by sethvargo** [chef/chef-rfc#32]
#### Specify gems to be loaded with Chef
 * **Breaks Backwards Compatibility? (Workstation):** No
 * **Breaks Backwards Compatibility? (Cookbooks):**  No
 * **User Benefit:** Med
  * Short description of the benefit: In certain situations, a developer may want to have a gem installed and loaded **before** Chef. This option (maybe in `Chef::Config`), would allow the user to specify a list of gems to load before booting Chef.
 * **Impact:** None
  * Short description of the impact: This would be a new feature, so there is no impact.

**Comment by lamont-granquist** [comment]
Pretty certain https://github.com/chef/chef-rfc/blob/master/rfc060-metadata-gem-installation.md addresses this.
