### ISSUE TITLE
RFC to reach consensus on which styling rules we should adhere as a community

### ISSUE THREAD

**Issue by sersut** [chef/chef-rfc#39]
Recently there has been a lot of discussions / ideas around the styling rules we should adhere to as a community. I think this has 2 different but related aspects

1. Styling guidelines for cookbooks
1. Styling guidelines for the Chef codebase

We should have an RFC to discuss and reach consensus on the set to rules that we believe is the right one. As a result of this RFC we can make sure that Chef DK does the necessary plumbing to set these rules up in its generators and we can enable enforcers on travis to make sure all the code going into Chef is of same style.

**Comment by lamont-granquist** [comment]
We created chefstyle for chef/chef and related codebases:  https://github.com/chef/chefstyle

**Comment by lamont-granquist** [comment]
I also created cookstyle for cookbooks:  https://github.com/chef/cookstyle

I'm going to close this issue as being addressed.  Its possible that we should formalize some RFC someplace which states that chefstyle shall be used for ruby projects related to chef/chef and that cookstyle shall be used on cookbooks.  But that's about all there is useful to say about policy.  The actual individual rules need to be argued about in PRs against the projects where the code is getting fixed.
