### ISSUE TITLE
Remove CHEF-3694 warning until we know what to do about it

### ISSUE THREAD

**Issue by pdf** [chef/chef-rfc#46]
With the vast proliferation of resource cloning in community cookbooks, and no clear direction on what to do about it, retaining this warning in the mean time simply makes Chef runs unparseable for mere mortals, and achieves absolutely nothing other than frustrating regular users.

It should obviously be re-instated in good time to allow people to migrate once there is a sensible path defined to do so.  This path should probably exist as an RFC here.

**Comment by lamont-granquist** [comment]
The 3694 warning messages for trivial resource cloning were suppressed in 12.1.0:  https://github.com/chef/chef/pull/2624

Also working on laying the groundwork to remove resource cloning completely for Chef 13:  https://github.com/chef/chef/pull/4838

I think that is working towards the direction which addresses all the concerns in here.  And the chef_version and ohai_version metadata has been shipped as well...
